name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Simple Test
      run: echo "Running simple test" && exit 0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key .env $USERNAME@$SERVER_IP:/home/ubuntu/app/.env
        ssh -i private_key $USERNAME@$SERVER_IP "echo 'Deployment complete'"
